name: run python scripts
on:
  schedule:
    - cron: '*/27 * * * *'
  workflow_dispatch:

jobs:
  name:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo contents
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: get packages
        run: |
          python -m pip install --upgrade pip
          python install -r pythonFiles/requirements.txt

      - name: run main.py
        run: pythonFiles/main.py
        env:
          SESSION: secrets.SESSION
