name: run python scripts
on: push

jobs:
  name:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: get packages
        run: |
          python -m pip install --upgrade pip
          python install -r Scracth_FrontPage/requirements.txt

      - name: run scratch frontpage
        run: python Scratch_FrontPage/main.py
        env:
          SESSION: secrets.SESSION
