name: run python scripts
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  START_PYTHON_SERVER:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo contents
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: get packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run python scripts
        run: python scratchFrontPage.py
        env:
          SESSION: ".eJxVT0tPwzAM_i85byV9JtmNTUKTeAgmJOBUuY67hbbJ1HYMgfjvONIuu9nfy59_xWmi0cNAYiV24G0YNsHSaEwqxULUcJoPdZTUzrKi0iYvKpUzNdM0Ywidi85zGDuy14YGsCMfXREjPzuE2QWfXIgp2dGxv4Dri5hzAw9sQiNTxLJJM5kXSLLRrW1kmcuyygvIYbV9XH69dd8Pd132cv-q1vX2-N63_ea5PHNMH_bOL92Rk4xMslQnaZUlqSpiyR78_gT72JxvLYT9ZCDUsxvoJ_gI3w40crWbJzrXH_zc9WsHmA4xWKOGpjRKEyljNUhEbohG8a4AqVUIElrx9w8M3XQv:1qbQvA:eihxwcRRpXlRaqmWLtVNgu3wOyk"
